spring.application.name=user-service-api

server.port=8082

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/user_service_api_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
spring.security.oauth.resourceserver.jwt.token-uri=http://localhost:8080/realms/quick-cart/protocol/openid-connect/token
spring.security.oauth.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/quick-cart
public.key.string=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0EJhyTlti+/pbQ6VLevz/aWCkcYFqC/Z3+0ecnMQJU8s8z6upbx34DBZs16uf7r/JtJFVIeALoaJEsgwz3KWy3jbD9mYFiczSkpKCcGCLB8kW4Taqtc5r7Xm5AbnLiiHWuCnTxhaXt9MRqch/Wbx03lLMUI6Ytb3mY46LFWVVXO70LDkFN0ZZsOOsUow6NLHZVS+Jb8KF2GTc83G+KqcgIFvi2eH3XA3ZZ1oBOOCwdNv70kc21DojEFk3J+zzKkJE3MuEk780hg89zW/TGNHeAQsZClYZ99eYqpCSYdRLS5rg/yb9cKeR9mcvxr0ohVWmvn4MWNWcTbSVOm0neBZ1wIDAQAB
keycloak.config.realm=quick-cart
keycloak.config.server-url=localhost:8080
keycloak.config.client-id=quick-cart-client
keycloak.config.grant-type=password
keycloak.config.name=gihansaduh@gmail.com
keycloak.config.secret=zoComfrrw1oaKyrZEU8RESWEAg9OHrbA
keycloak.config.password=1234
emailKey=jakjhjfgdhjfghjhjashjk
fromEmail=gihansaduh@gmail.com